## Configuration File 
exp_name: test
seed: 0
model: generator_aldous-pacman_4
test_set: test_set_mix
student:
  hid: -1
  l: 1
  gamma: 0.99
  epochs: 100
  gpu_id: -1
  ent_coef: 0.005
  max_ep_len: 2000
  steps_per_ep: 10000
  buf_size: 2000000
  nb_test_episodes: 30
  lr: 0.001
  train_freq: 10
  batch_size: 1000
  actor: convolutional
  clip_ratio: 0.2
  pi_lr: 0.0003
  vf_lr: 0.001
  train_pi_iters: 10
  train_v_iters: 10
  lam: 0.97
  target_kl: 0.01
  save_freq: 10
  test_freq: 1
  epochs_per_task: 10
teacher:
  teacher: Random
  gmm_fitness_fun: null
  nb_em_init: null
  min_k: null
  max_k: null
  fit_rate: null
  weighted_gmm: true
  alp_max_size: null
  absolute_lp: true
  max_region_size: null
  alp_window_size: null